apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
    app: mongo
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 # Replace this IP with Server1(10.10.15.60) or Server2(10.10.15.63) or Server3(10.10.15.64) dependending on your linux user 
    path: /var/nfs/jegan/mongodb # Replace this path with /mnt/nfs/user01/mongodb folder
