apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: tektutorjegan.jfrog.io/tektutor-docker/openshift-hello-ms:1.0.0
        name: hello
      imagePullSecrets:
      - name: private-jfrog-image-registry

