apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: tektutor-cluster
spec:
  kafka:
    # ...
    listeners:
      # ...
      - name: listener1
        port: 9094
        type: route
        tls: true
